// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_id_ from "./routes/[id].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_entries_id_ from "./routes/api/entries/[id].ts";
import * as $api_entries_index from "./routes/api/entries/index.ts";
import * as $index from "./routes/index.tsx";
import * as $EntryArticle from "./islands/EntryArticle.tsx";
import * as $Journal from "./islands/Journal.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[id].tsx": $_id_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/entries/[id].ts": $api_entries_id_,
    "./routes/api/entries/index.ts": $api_entries_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/EntryArticle.tsx": $EntryArticle,
    "./islands/Journal.tsx": $Journal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
